name: Daily Release

on:
  schedule:
    - cron: '0 0 * * *'  # This means the action will run at 00:00 (midnight) UTC every day.

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'  # Replace with your Node.js version
      - name: Install Dependencies
        run: yarn install
      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn semantic-release
